import os
import re
import csv
import gzip
import json
import shutil
import random
import hashlib
import numpy as np
import pandas as pd
from Bio import SeqIO
from pathlib import Path
from collections import defaultdict

singularity: config['sif']
include: "rules/common.smk"

from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider
FTP = FTPRemoteProvider()

from snakemake.remote.S3 import RemoteProvider as S3RemoteProvider
s3_key_id = os.environ.get('AWS_ACCESS_KEY')
s3_access_key = os.environ.get('AWS_SECRET_KEY')

S3 = S3RemoteProvider(
    endpoint_url='https://s3.msi.umn.edu',
    access_key_id=s3_key_id,
    secret_access_key=s3_access_key
)

# small
units_small = pd.read_table(config['samples'], dtype=str) \
    .set_index(['sample', 'tissue'], drop=False) \
    .sort_index()

num_tissues = len(units_small['tissue'].unique().tolist())

rule all:
    input:
       #######################
       ## MAIN PIPELINE
       #######################
        S3.remote(
            expand(
                '{bucket}/private/small/quant/isomirmap/{release}/merge/isomir_descript.tsv',
                u=units_small.itertuples(), 
                bucket=config['bucket'], 
                release=[
                    'Equus_caballus.EquCab3.0.103'
                ],
                exp=['cts','rpm']
            )
        ),
        S3.remote(
            expand(
                '{bucket}/private/fastq/process_fastqs_counts.csv',
                bucket=config['bucket']
            )
        ),
       #S3.remote(
       #    expand(
       #        '{bucket}/private/small/align/bowtie/{release}/all_samples.featcts.csv',
       #        bucket=config['bucket'], 
       #        release=[
       #           #'GCF_002863925.1_EquCab3.0',
       #            'Equus_caballus.EquCab3.0.103'
       #        ],
       #    )
       #),

# ----------------------------------------------------------
#       various plots
# ----------------------------------------------------------

#include: 'rules/viz.smk'

# ----------------------------------------------------------
#       small rna processing and quant
# ----------------------------------------------------------

include: 'rules/make_nice.smk'
include: 'rules/process_small.smk'
include: 'rules/featcts_small.smk'
include: 'rules/filters.smk'
include: 'rules/mirpro.smk'
include: 'rules/novel.smk'
include: 'rules/mapping_bundle.smk'

# ----------------------------------------------------------
#       QC
# ----------------------------------------------------------

include: 'rules/qc.smk'

